<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ServiceGallery extends Model
{
    //

    public function service()
    {
        return $this->belongsTo(Service::class, 'service_id');
    }

    public function delete()
    {
        @unlink(storage_path('uploads/services/').$this->image);
        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
