<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Testimonial extends Model
{
    //
    public function details()
    {
        return $this->hasMany(TestimonialTrans::class ,'testimonial_id');
    }

    public function arabic()
    {
        return $this->details()->where('lang' , 'ar')->first();
    }

    public function english()
    {
        return $this->details()->where('lang' , 'en')->first();
    }

    public function translated(){
        return $this->details()->where('lang' ,app()->getLocale())->first();
    }

    public function delete()
    {
        @unlink(storage_path('uploads/testimonials/').$this->image);
        $this->details()->delete();
        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
