<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Video extends Model
{
    //
    public function delete()
    {
        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
